### ISSUE TITLE
Problema di sicurezza: utilizzando HTML con impostazione predefinita per Toast/Tooltips/Autocomplete esponi un XSS

### ISSUE THREAD

**Issue by MKokeshi** [LemuelPuglisi/DmiStorageClient#9]
### Comportamento Attuale
Da default quando tu aggiungi contenuti dinamici come Toast, Tooltips and autocomplete tu puoi injectare degli input data come HTML.
I dati di input dovrebbero essere sanificati oppure si usa: jquery.text('untrustData') o jquery.html('untrustData') o innerHTML = 'untrustData'.

### Possibile Soluzione
Se vuoi consentire l'HTML, e non sanificare l'html/non consentire javascript e l'utente finale desidera consentire HTML/javascript, puoi aggiungere una nuova configurazione con un parametro come
options : {allowUnsafeData: true}

### Toasts
`var userId = '<IFRAME SRC="javascript:alert(document.cookie);"></IFRAME>'
M.toast({html: 'userId: ${userId} fail'})`
### Tooltips
`<a class="btn tooltipped" data-position="bottom" data-tooltip="<IFRAME SRC='javascript:alert(document.cookie);'></IFRAME></script>">Hover me!</a>`
### Autocomplete
`$('input.autocomplete').autocomplete({
    data: {
	    "Apple": "\"><IFRAME SRC=\"javascript:alert(document.cookie);\"></IFRAME>",
	    "Microsoft": null,
	    "Google": 'https://placehold.it/250x250',
    }
});`

### Come prevenire Attacchi XSS

- Disinfetta l'input dei dati in una richiesta HTTP prima di rispecchiarlo, assicurandosi che tutti i dati siano convalidati, filtrati o di cui è stato eseguito l'escape prima di restituire qualsiasi cosa all'utente, come i valori dei parametri di query durante le ricerche.
- Converti caratteri speciali come `?, &, /, <,>` e gli spazi nei rispettivi equivalenti codificati in HTML o URL.
- Dai agli utenti l'opzione di disattivare gli script client-side
- Reindirizza le richieste non valide.
- Rileva gli accessi simultanei, inclusi quelli da due indirizzi IP separati, e annulla tali sessioni.

**Comment by LemuelPuglisi** [comment]
Ciao Giuseppe, sono felice che tu contribuisca! Tuttavia il progetto non è più mantenuto (non è stato neanche deployato alla fine) perché ero il solo a svilupparlo. Concordo sulle vulnerabilità :) 
Se sei interessato a contribuire posso aggiungerti nel gruppo telegram degli sviluppatori UniCT dove troverai molti progetti attualmente in sviluppo. In tal caso mandami un messaggio (sempre su Telegram, @charlemgn)
